modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/Mnesikos/SimplyCats/issues" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/simply-cats/" #optional
#logoFile="simplycats.png" #optional
credits="Thank you Captain and fisk for the extra texture help! <3 Also big thanks to Ms. Random and Soggy for dealing with my lack of proper coding know-how. (:" #optional
authors="Mnesikos" #optional
[[mods]] #mandatory
modId="simplycats" #mandatory
version="${version}" #mandatory
displayName="Simply Cats" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
Cats! Cats everywhere!
'''
[[dependencies.simplycats]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"