modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Mnesikos/SimplyCats/issues"

[[mods]]
    modId="simplycats"
    version="${file.jarVersion}"
    displayName="Simply Cats"
    updateJSONURL="https://raw.githubusercontent.com/Mnesikos/SimplyCats/forge/1.16.5/versions.json"
    displayURL="https://github.com/Mnesikos/SimplyCats/wiki"
    logoFile="logo.png"
    credits="Fisk, Mango, Jamie, Ms. Random, Sekelsta"
    authors="Mnesikos"
    description='''
For a very, very long time the cats of Minecraft have been neglected. This mod aims to change that, breathing a whole new life into the soft little fluff balls of hate.
    '''
[[dependencies.simplycats]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplycats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
